# Enable Build Analysis
APP:
   ENVIRONMENT: dev
   DEBUG: True
   # Only accept True or False
   BIND: 0.0.0.0:5005
   WORKERS: 1
   PROTOCOL: http://
   TIMEOUT: 3600
   CELERY_ENABLED: True
   # Only accept True or False

OBJECT_STORAGE:
      ENDPOINT: http://isd-minio:9000
      BUCKET_NAME: autopilot
POSTGRES:
      USERNAME: 'spinnaker'
      PASSWORD: 'yA4QmcTmws!#q5lV'
      HOST: opsmx-spinnaker-postgres-1.cdswufymuxfo.us-east-1.rds.amazonaws.com 
      PORT: 5432
      DB: autopilotqueue

RABBITMQ:
      USERNAME: 'rabbitmq'
      PASSWORD: 'Networks123'
      HOST: rabbitmq-service
      PORT: 5672
